import { promises as fs, existsSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import type { Compilation, Compiler } from "@rspack/core";
import { parseWasm } from "../tools";
import { getWasmESMBinding, getWasmModuleBinding } from "./runtime/binding";
import { getPluginUtils } from "./runtime/utils";
import {
  escapeRegExp,
  sha1,
  UMWASM_HELPERS_ID,
  UNWASM_EXTERNAL_PREFIX,
  UnwasmPluginOptions,
  WasmAsset,
} from "./shared";

export type { UnwasmPluginOptions } from "./shared";

const WASM_ID_RE = /\.wasm(?:\?.*)?$/i;

/**
 * Rspack module identifiers travel through the native (Rust) side, so the `\0`
 * prefixes the Rollup plugin uses for virtual ids are replaced with plain,
 * filesystem-safe schemes before the generated code reaches the bundler.
 */
const EXTERNAL_PREFIX = "unwasm-external:";
const EXTERNAL_RE = /unwasm-external:([^"']+)/gu;

const PLUGIN_NAME = "unwasm";

/** Suffix of the virtual modules holding the generated bindings. */
const BINDING_SUFFIX = ".unwasm.mjs";

/**
 * Rspack resolves loaders by path, so this ships as a plain `.cjs` file next to
 * the built plugin (see `build.config.ts`) rather than being bundled into it.
 */
const DEPENDENCY_LOADER = join(import.meta.dirname, "rspack-loader.cjs");

/** Requests carrying inline loader syntax are left to rspack's own resolver. */
const INLINE_LOADER_RE = /!/;

/**
 * JS output assets, the only ones that can carry an external specifier. Asset
 * names may end with a query (`[name].js?[contenthash]`), so match beyond `$`.
 */
const JS_ASSET_RE = /\.[cm]?js(\?|$)/;

type WasmInterface = Pick<WasmAsset, "imports" | "exports">;

interface GeneratedBinding {
  /** Absolute path of the `.wasm` binary this binding was generated from. */
  resolved: string;
  /** Whether the import carried a `?module` query. */
  isModuleRequest: boolean;
  asset: WasmAsset;
}

/**
 * WebAssembly support for [rspack](https://rspack.rs).
 *
 * ```js
 * // rspack.config.mjs
 * import { unwasmRspack } from "unwasm/plugin/rspack";
 *
 * export default {
 *   plugins: [unwasmRspack({ esmImport: true })],
 * };
 * ```
 */
export function unwasmRspack(opts: UnwasmPluginOptions = {}): UnwasmRspackPlugin {
  return new UnwasmRspackPlugin(opts);
}

export class UnwasmRspackPlugin {
  readonly name = PLUGIN_NAME;

  constructor(private readonly opts: UnwasmPluginOptions = {}) {}

  apply(compiler: Compiler): void {
    const opts = this.opts;
    const { experiments, ExternalsPlugin, sources } = compiler.rspack;

    // Keyed by content hash, so this stays valid across rebuilds.
    const parseCache: Record<string, WasmInterface> = Object.create(null);

    const helpersId = join(compiler.context, "unwasm-helpers.mjs");

    // Generated bindings are served from an in-memory layer instead of a loader,
    // which keeps the whole plugin in a single module and lets the (async) parse
    // step run during resolution. The virtual file store only exists once the
    // compiler is created, so the always-present helpers module is seeded here.
    const virtualModules = new experiments.VirtualModulesPlugin({
      [helpersId]: getPluginUtils(),
    });
    virtualModules.apply(compiler);

    // Ties each generated binding to the binary it came from, so that editing a
    // `.wasm` invalidates it on rebuild.
    compiler.options.module.rules.unshift({
      test: new RegExp(escapeRegExp(BINDING_SUFFIX) + "$"),
      type: "javascript/auto",
      use: [{ loader: DEPENDENCY_LOADER }],
    });

    if (opts.esmImport) {
      // Keep `import("unwasm-external:<name>")` in the output untouched; the
      // specifier is rewritten to a relative asset path in `processAssets`.
      // `module-import` keeps dynamic imports dynamic instead of hoisting them.
      new ExternalsPlugin("module-import", [new RegExp("^" + escapeRegExp(EXTERNAL_PREFIX))]).apply(
        compiler,
      );
    }

    /** Rewrite the shared binding output to identifiers rspack can resolve. */
    const rewriteIds = (code: string) =>
      code
        .replaceAll(UMWASM_HELPERS_ID, helpersId.replaceAll("\\", "/"))
        .replaceAll(UNWASM_EXTERNAL_PREFIX, EXTERNAL_PREFIX);

    /** Every binding generated by this compiler, keyed by its virtual module id. */
    const generated = new Map<string, GeneratedBinding>();

    // Warnings raised outside a compilation (see the `watchRun` hook below) are
    // buffered and flushed into the next one.
    const pendingWarnings: string[] = [];

    /**
     * Generate the binding for `resolved`, publish it as a virtual module and
     * return that module's id.
     */
    async function generate(
      resolved: string,
      isModuleRequest: boolean,
      onWarn: (message: string) => void,
    ): Promise<string> {
      const source = await fs.readFile(resolved);
      const name = `wasm/${basename(resolved, ".wasm")}-${sha1(source)}.wasm`;

      let isModule = isModuleRequest;
      let parsed: WasmInterface = { imports: {}, exports: ["default"] };
      if (!isModule) {
        try {
          parsed = parseCache[name] ||= parseInterface(source, name);
        } catch (error) {
          onWarn(
            `Failed to parse the WebAssembly module "${resolved}"; falling back to module mode: ${(error as Error).message}`,
          );
          isModule = true;
        }
      }

      const asset: WasmAsset = { name, id: resolved, source, ...parsed };

      const code = rewriteIds(
        isModule
          ? await getWasmModuleBinding(asset, opts)
          : await getWasmESMBinding(asset, opts).catch(async (error) => {
              onWarn(
                `Failed to load the WebAssembly module "${resolved}"; falling back to module mode: ${(error as Error).message}`,
              );
              return getWasmModuleBinding(asset, opts);
            }),
      );

      // Generated bindings sit next to the binary so that relative imports and
      // `node_modules` lookups from within them keep resolving. The request mode
      // is part of the id: one binary may be imported both plainly and as
      // `?module` within a single build.
      const virtualId = join(
        dirname(resolved),
        `${basename(resolved)}${isModuleRequest ? ".module" : ""}${BINDING_SUFFIX}`,
      );
      virtualModules.writeModule(virtualId, code);
      generated.set(virtualId, { resolved, isModuleRequest, asset });
      return virtualId;
    }

    // On a rebuild rspack replays the already-rewritten request for cached
    // dependencies, so `beforeResolve` never sees the `.wasm` id again. Refresh
    // every known binding up front so edits to a binary actually propagate.
    compiler.hooks.watchRun.tapPromise(PLUGIN_NAME, async () => {
      await Promise.all(
        [...generated.values()].map((entry) =>
          existsSync(entry.resolved)
            ? generate(entry.resolved, entry.isModuleRequest, (m) => pendingWarnings.push(m))
            : undefined,
        ),
      );
    });

    compiler.hooks.compilation.tap(
      PLUGIN_NAME,
      (compilation, { normalModuleFactory: moduleFactory }) => {
        const resolver = moduleFactory.getResolver("normal", {});

        // Keep binaries resolved by earlier builds in the watch set; their
        // requests are cached and will not pass through `beforeResolve` again.
        for (const entry of generated.values()) {
          compilation.fileDependencies.add(entry.resolved);
        }

        moduleFactory.hooks.beforeResolve.tapPromise(PLUGIN_NAME, async (data) => {
          const request = data.request;

          // `unwasm-external:wasm/<name>.wasm` also matches `WASM_ID_RE`.
          if (
            request.startsWith(EXTERNAL_PREFIX) ||
            INLINE_LOADER_RE.test(request) ||
            !WASM_ID_RE.test(request)
          ) {
            return;
          }

          const [bareRequest, query = ""] = splitQuery(request);

          // `resolveSync` throws rather than returning `false` when a request
          // cannot be resolved; let rspack report it with its own diagnostics.
          let resolved: string | false;
          try {
            resolved = resolver.resolveSync({}, data.context, bareRequest);
          } catch {
            return;
          }
          if (!resolved || !existsSync(resolved)) {
            return;
          }

          // Registers the binary for watch mode; `data.fileDependencies` alone
          // does not survive into the compilation's watch set.
          compilation.fileDependencies.add(resolved);

          // Matches `?module` anywhere in the query, so `?module&foo` and
          // `?foo&module` behave the same as the bare `?module` the Rollup
          // plugin looks for.
          const isModuleRequest = query.split("&").includes("module");

          data.request = await generate(resolved, isModuleRequest, (message) =>
            warn(compilation, opts, message),
          );
        });

        compilation.hooks.processAssets.tap(
          {
            name: PLUGIN_NAME,
            // Ahead of `OPTIMIZE_SIZE` (minification) and `DEV_TOOLING` (source
            // maps), so both observe the rewritten specifier. Rewriting after
            // `DEV_TOOLING` leaves the already-emitted `.map` describing the
            // longer `unwasm-external:` text, shifting every later column.
            // All chunk assets exist by `OPTIMIZE`.
            stage: compiler.rspack.Compilation.PROCESS_ASSETS_STAGE_OPTIMIZE,
          },
          () => {
            for (const message of pendingWarnings.splice(0)) {
              warn(compilation, opts, message);
            }

            // Drop bindings whose module is no longer in the graph, e.g. after
            // an import was removed in watch mode. They would otherwise be
            // regenerated on every rebuild for the compiler's lifetime, and
            // keep their binary in the watch set. Skipped on a failed build,
            // where the graph is incomplete and would prune live entries.
            if (compilation.errors.length === 0) {
              const live = new Set<string>();
              for (const module of compilation.modules) {
                const resource = (module as { resource?: string }).resource;
                if (resource && generated.has(resource)) {
                  live.add(resource);
                }
              }
              for (const virtualId of generated.keys()) {
                if (!live.has(virtualId)) {
                  generated.delete(virtualId);
                }
              }
            }

            if (!opts.esmImport) {
              return;
            }

            const byName = new Map(
              [...generated.values()].map((entry) => [entry.asset.name, entry.asset]),
            );

            // Rewrite first, recording which binaries this output actually
            // references; anything left over belongs to a stale build.
            const referenced = new Set<string>();
            for (const [fileName, source] of Object.entries(compilation.assets)) {
              if (!JS_ASSET_RE.test(fileName)) {
                continue;
              }
              const code = source.source().toString();
              if (!code.includes(EXTERNAL_PREFIX)) {
                continue;
              }
              // Output filenames are `/`-separated regardless of platform.
              const nestedLevel = fileName.split("/").filter(Boolean).length - 1;
              const prefix = nestedLevel > 0 ? "../".repeat(nestedLevel) : "./";
              // `ReplaceSource` carries the chunk's existing mappings through
              // the edit, so the later `DEV_TOOLING` stage still emits a map
              // that points at the original binding. A `RawSource` would
              // discard them.
              const rewritten = new sources.ReplaceSource(source);
              let changed = false;
              for (const match of code.matchAll(EXTERNAL_RE)) {
                const name = match[1];
                if (!byName.has(name)) {
                  warn(compilation, opts, `Failed to resolve WASM import: ${JSON.stringify(name)}`);
                  continue;
                }
                referenced.add(name);
                // End offsets are inclusive.
                rewritten.replace(match.index, match.index + match[0].length - 1, prefix + name);
                changed = true;
              }
              if (changed) {
                compilation.updateAsset(fileName, rewritten);
              }
            }

            for (const name of referenced) {
              compilation.emitAsset(name, new sources.RawSource(byName.get(name)!.source));
            }
          },
        );
      },
    );
  }
}

// --- Utils ---

function splitQuery(id: string): [string, string?] {
  const index = id.indexOf("?");
  return index === -1 ? [id] : [id.slice(0, index), id.slice(index + 1)];
}

function warn(compilation: Compilation, opts: UnwasmPluginOptions, message: string) {
  if (!opts.silent) {
    compilation.warnings.push(new Error(`[unwasm] ${message}`) as any);
  }
}

/** Read a module's imports and exports. Throws if the binary cannot be parsed. */
function parseInterface(source: Buffer, name: string): WasmInterface {
  const imports: Record<string, string[]> = Object.create(null);
  const exports: string[] = [];

  const parsed = parseWasm(source, { name });
  for (const mod of parsed.modules) {
    exports.push(...mod.exports.map((e) => e.name));
    for (const imp of mod.imports) {
      (imports[imp.module] ||= []).push(imp.name);
    }
  }

  return { imports, exports };
}
