name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: npm i -g --force corepack
      - run: corepack enable
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint
        if: ${{ matrix.os != 'windows-latest' }}
      - run: pnpm test:types
        if: ${{ matrix.os != 'windows-latest' }}
      - run: pnpm build
        if: ${{ matrix.os != 'windows-latest' }}
      - run: pnpm vitest --coverage
      - uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
